### ISSUE TITLE
Search is not working

### ISSUE THREAD

**Issue by Sachin9822** [StudioKeys/vendor_PixelLauncher#1]
![image](https://user-images.githubusercontent.com/70788804/197319781-2b196453-5cb0-4e1d-ad8a-a8b1a622b534.png)

**Comment by StudioKeys** [comment]
Give logs along with the issue occurred. A screenshot alone wont help anything

**Comment by Sachin9822** [comment]
[search_not_working.txt](https://github.com/StudioKeys/vendor_PixelLauncher/files/9862343/search_not_working.txt)
@StudioKeys here are the logs

**Comment by StudioKeys** [comment]
Try the latest version which is updated now
