### ISSUE TITLE
Fullmod variant incongruence 

### ISSUE THREAD

**Issue by simple-sunrise** [StudioKeys/vendor_PixelLauncher#2]
Fullmod1 installs the at glance type 2 and fullmod2 installs the at a glance type 1

**Comment by StudioKeys** [comment]
U are using an old versions then its been fixed on latest releases :)

**Comment by simple-sunrise** [comment]
@StudioKeys Can you please refer to me where can I find the latest release because yesterday I cloned branch 13 and faced that incongruence :)

**Comment by StudioKeys** [comment]
Use the 13 branch of now its updated

**Comment by StudioKeys** [comment]
Refer commit 59ffa379ef77a79663fbd03a66470a23659f1d0d for the fix!
