### ISSUE TITLE
"Close All" in Recent Apps

### ISSUE THREAD

**Issue by Vol4ikk** [StudioKeys/vendor_PixelLauncher#3]
G-day
Can you add a "Close All" button in recent open apps? Your launcher is the best for Pixel 7, but this feature is really missing
Have a good day!

**Comment by Ardjlon** [comment]
> G-day Can you add a "Close All" button in recent open apps? Your launcher is the best for Pixel 7, but this feature is really missing Have a good day!

It's on the left side, just after the last open app, and i think not way to add like another launchers
